import { envString } from './env.js'

// TODO(platform-api): Surface the real OpenAPI specification generated by PostgREST.
export const getProjectRestDefinition = (ref: string) => ({
  swagger: '2.0',
  info: {
    title: `${ref} REST API`,
    description: 'Stubbed definition – replace with live PostgREST metadata.',
    version: '1.0.0',
  },
  paths: {},
  definitions: {},
})

// TODO(platform-api): Generate scoped API keys once service role management is in place.
export const createTemporaryApiKey = () => ({
  api_key: envString('SUPABASE_SERVICE_KEY') ?? envString('SERVICE_KEY') ?? 'service-role-key',
})
