services:
  platform-api:
    image: node:22-alpine
    environment:
      SUPABASE_TELEMETRY_DISABLED: "true"
      PLATFORM_API_REPO_ROOT: /workspace
      PLATFORM_PROJECTS_ROOT: ${PWD}/platform-projects
      PLATFORM_ORCHESTRATOR_URL: http://runtime-agent:8085
      PLATFORM_ORCHESTRATOR_TOKEN: ${PLATFORM_ORCHESTRATOR_TOKEN:-supabase-runtime-agent}
      PORT: "4210"
      HOST: "0.0.0.0"
      CI: "true"
    command: >
      sh -c "apk add --no-cache bash curl git jq openssl tar \
        && corepack enable pnpm \
        && pnpm install --filter platform-api... \
        && pnpm --filter platform-api... dev"
    working_dir: /workspace
    env_file:
      - .env
    volumes:
      - ..:/workspace
      - platform-api-data:/workspace/apps/platform-api/data
      - ${PWD}/platform-projects:${PWD}/platform-projects
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "4210:4210"
    depends_on:
      - db
      - runtime-agent
    container_name: platform-dev

  runtime-agent:
    build:
      context: ..
      dockerfile: apps/runtime-agent/Dockerfile
    container_name: runtime-agent
    environment:
      RUNTIME_AGENT_LISTEN_ADDR: ":8085"
      RUNTIME_AGENT_COMMAND_TIMEOUT: 15m
      RUNTIME_AGENT_SUPABASE_HOST: host.docker.internal
      RUNTIME_AGENT_AUTH_TOKEN: ${PLATFORM_ORCHESTRATOR_TOKEN:-supabase-runtime-agent}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${PWD}/platform-projects:${PWD}/platform-projects
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

volumes:
  platform-api-data:
