services:
  platform-api:
    build:
      context: ..
      dockerfile: apps/platform-api/Dockerfile
    environment:
      PORT: "4000"
      HOST: "0.0.0.0"
      PLATFORM_API_REPO_ROOT: /workspace
    volumes:
      - platform-api-data:/app/apps/platform-api/data
      - ..:/workspace:ro
    depends_on:
      - db
    restart: unless-stopped

  studio:
    environment:
      NEXT_PUBLIC_IS_PLATFORM: "true"
      NEXT_PUBLIC_API_URL: http://platform-api:4000/platform
    depends_on:
      - platform-api

volumes:
  platform-api-data:
